services:
  - type: web
    name: hidden-places-backend
    env: node
    plan: free
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        value: your_database_connection_url
      - key: JWT_SECRET
        value: f0aa2d5b9e6c4cda84dce24b1dc989f1f7c5e0917a9a445ca17f6aee7b9e3b3a
      - key: CLOUDINARY_API_KEY
        value: 656737621213859
      - key: CLOUDINARY_API_SECRET
        value: WwCM_Yg2JuLksmb4i4gngHlWN44
      - key: CLOUDINARY_CLOUD_NAME
        value: dpvagqlky
